server:
  port: 10273

jwt:
  header: Authorization
  secret: 1234

# 引入logger日志相关配置
logging:
  config: classpath:logback-spring.xml


spring:
  datasource:
    #   数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:13306/dpe_flowable?&nullCatalogMeansCurrent=true&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: 123456

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # mapper映射包扫描
  type-aliases-package: com.fir.flow.entity # entity别名

  # 开启mybatis sql日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


flowable:
  # 关闭异步定时任务：如果要是启动事件，则需要开启该配置
  async-executor-activate: false


swagger:
  enable: true
